"""
Property-based tests for existing order immutability under commercial flag changes.

Feature: commercial-account-management, Property 4: Existing order immutability under flag changes

Validates: Requirements 5.1, 5.2
"""
import copy
import uuid
from hypothesis import given, settings
from hypothesis import strategies as st


# --- Domain Model ---


def make_order(
    order_id: str,
    customer_id: str,
    order_type: str,
    pay_by_invoice: bool,
    status: str,
    total_amount: float,
    frequency_id: str | None = None,
) -> dict:
    """Create an order dict representing a row in orders.orders."""
    return {
        "order_id": order_id,
        "customer_id": customer_id,
        "order_type": order_type,
        "pay_by_invoice": pay_by_invoice,
        "status": status,
        "total_amount": total_amount,
        "frequency_id": frequency_id,
    }


# --- Simulation of flag toggle ---


def toggle_customer_commercial_flag(
    customer: dict, new_is_commercial: bool, existing_orders: list[dict]
) -> tuple[dict, list[dict]]:
    """
    Simulate toggling the is_commercial flag on a customer account.

    Per the specification, this operation:
    - Updates the customer record's is_commercial field
    - Does NOT modify any existing orders

    Returns the updated customer and the (unchanged) existing orders.
    """
    updated_customer = {**customer, "is_commercial": new_is_commercial}
    # The key safety guarantee: existing orders are NEVER modified.
    # We return the same list without touching it.
    return updated_customer, existing_orders


def toggle_frequency_commercial_flag(
    frequency: dict, new_is_commercial: bool, existing_orders: list[dict]
) -> tuple[dict, list[dict]]:
    """
    Simulate toggling the is_commercial flag on a frequency record.

    Per the specification, this operation:
    - Updates the frequency record's is_commercial field
    - Does NOT modify any existing orders generated by that frequency

    Returns the updated frequency and the (unchanged) existing orders.
    """
    updated_frequency = {**frequency, "is_commercial": new_is_commercial}
    # The key safety guarantee: existing orders are NEVER modified.
    return updated_frequency, existing_orders


# --- Strategies ---


_order_type_strategy = st.sampled_from(["Online", "InStore", "Commercial"])
_status_strategy = st.sampled_from([
    "Pending", "Confirmed", "PickedUp", "Processing",
    "ProcessingCompleted", "OutForDelivery", "Delivered", "Cancelled"
])
_amount_strategy = st.floats(min_value=0.0, max_value=10000.0, allow_nan=False, allow_infinity=False)
_uuid_strategy = st.uuids().map(str)


@st.composite
def order_strategy(draw):
    """Generate a random order dict."""
    return make_order(
        order_id=draw(_uuid_strategy),
        customer_id=draw(_uuid_strategy),
        order_type=draw(_order_type_strategy),
        pay_by_invoice=draw(st.booleans()),
        status=draw(_status_strategy),
        total_amount=round(draw(_amount_strategy), 2),
        frequency_id=draw(st.one_of(st.none(), _uuid_strategy)),
    )


_existing_orders_strategy = st.lists(order_strategy(), min_size=0, max_size=20)


@st.composite
def customer_strategy(draw):
    """Generate a random customer dict with commercial fields."""
    return {
        "customer_id": draw(_uuid_strategy),
        "email": draw(st.one_of(st.none(), st.emails())),
        "billing_email": draw(st.one_of(st.none(), st.emails())),
        "is_commercial": draw(st.booleans()),
    }


@st.composite
def frequency_strategy(draw):
    """Generate a random frequency record dict."""
    return {
        "frequency_id": draw(_uuid_strategy),
        "customer_id": draw(_uuid_strategy),
        "laundry_id": draw(_uuid_strategy),
        "is_active": draw(st.booleans()),
        "is_commercial": draw(st.booleans()),
    }


# --- Property Tests ---


class TestExistingOrderImmutabilityProperty:
    """Property 4: Existing order immutability under flag changes.

    For any set of existing orders in the database, toggling the is_commercial
    flag on either the customer account or a frequency record SHALL NOT modify
    any field of those existing orders.

    **Validates: Requirements 5.1, 5.2**
    """

    @given(
        customer=customer_strategy(),
        existing_orders=_existing_orders_strategy,
        new_is_commercial=st.booleans(),
    )
    @settings(max_examples=200)
    def test_customer_flag_toggle_preserves_all_order_fields(
        self, customer, existing_orders, new_is_commercial
    ):
        """Toggling is_commercial on a customer account does not modify any
        field of any existing order (Requirement 5.2)."""
        # Deep copy to compare before and after
        orders_before = copy.deepcopy(existing_orders)

        # Perform the toggle
        _updated_customer, orders_after = toggle_customer_commercial_flag(
            customer, new_is_commercial, existing_orders
        )

        # Verify every order is identical field-by-field
        assert len(orders_after) == len(orders_before), (
            f"Order count changed: {len(orders_before)} -> {len(orders_after)}"
        )
        for i, (before, after) in enumerate(zip(orders_before, orders_after)):
            assert before == after, (
                f"Order at index {i} was modified after customer flag toggle. "
                f"Before: {before}, After: {after}"
            )

    @given(
        frequency=frequency_strategy(),
        existing_orders=_existing_orders_strategy,
        new_is_commercial=st.booleans(),
    )
    @settings(max_examples=200)
    def test_frequency_flag_toggle_preserves_all_order_fields(
        self, frequency, existing_orders, new_is_commercial
    ):
        """Toggling is_commercial on a frequency record does not modify any
        field of any existing order generated by that frequency (Requirement 5.1)."""
        # Deep copy to compare before and after
        orders_before = copy.deepcopy(existing_orders)

        # Perform the toggle
        _updated_frequency, orders_after = toggle_frequency_commercial_flag(
            frequency, new_is_commercial, existing_orders
        )

        # Verify every order is identical field-by-field
        assert len(orders_after) == len(orders_before), (
            f"Order count changed: {len(orders_before)} -> {len(orders_after)}"
        )
        for i, (before, after) in enumerate(zip(orders_before, orders_after)):
            assert before == after, (
                f"Order at index {i} was modified after frequency flag toggle. "
                f"Before: {before}, After: {after}"
            )

    @given(
        customer=customer_strategy(),
        frequency=frequency_strategy(),
        existing_orders=_existing_orders_strategy,
    )
    @settings(max_examples=200)
    def test_repeated_toggles_preserve_all_order_fields(
        self, customer, frequency, existing_orders
    ):
        """Multiple sequential toggles (True→False→True) on both customer and
        frequency records still leave all existing orders untouched."""
        orders_before = copy.deepcopy(existing_orders)

        # Toggle customer flag: False → True → False
        _, orders_after_step1 = toggle_customer_commercial_flag(
            customer, True, existing_orders
        )
        updated_customer = {**customer, "is_commercial": True}
        _, orders_after_step2 = toggle_customer_commercial_flag(
            updated_customer, False, orders_after_step1
        )

        # Toggle frequency flag: False → True → False
        _, orders_after_step3 = toggle_frequency_commercial_flag(
            frequency, True, orders_after_step2
        )
        updated_frequency = {**frequency, "is_commercial": True}
        _, orders_after_step4 = toggle_frequency_commercial_flag(
            updated_frequency, False, orders_after_step3
        )

        # After all toggles, orders must be unchanged
        assert len(orders_after_step4) == len(orders_before), (
            f"Order count changed after repeated toggles: "
            f"{len(orders_before)} -> {len(orders_after_step4)}"
        )
        for i, (before, after) in enumerate(zip(orders_before, orders_after_step4)):
            assert before == after, (
                f"Order at index {i} was modified after repeated toggles. "
                f"Before: {before}, After: {after}"
            )

    @given(
        customer=customer_strategy(),
        existing_orders=_existing_orders_strategy,
        new_is_commercial=st.booleans(),
    )
    @settings(max_examples=200)
    def test_order_ids_preserved_after_customer_toggle(
        self, customer, existing_orders, new_is_commercial
    ):
        """All order_id values are preserved after toggling customer commercial flag.
        No orders are added or removed."""
        ids_before = [o["order_id"] for o in existing_orders]

        _, orders_after = toggle_customer_commercial_flag(
            customer, new_is_commercial, existing_orders
        )

        ids_after = [o["order_id"] for o in orders_after]
        assert ids_before == ids_after, (
            f"Order IDs changed after customer toggle. "
            f"Before: {ids_before}, After: {ids_after}"
        )

    @given(
        frequency=frequency_strategy(),
        existing_orders=_existing_orders_strategy,
        new_is_commercial=st.booleans(),
    )
    @settings(max_examples=200)
    def test_order_ids_preserved_after_frequency_toggle(
        self, frequency, existing_orders, new_is_commercial
    ):
        """All order_id values are preserved after toggling frequency commercial flag.
        No orders are added or removed."""
        ids_before = [o["order_id"] for o in existing_orders]

        _, orders_after = toggle_frequency_commercial_flag(
            frequency, new_is_commercial, existing_orders
        )

        ids_after = [o["order_id"] for o in orders_after]
        assert ids_before == ids_after, (
            f"Order IDs changed after frequency toggle. "
            f"Before: {ids_before}, After: {ids_after}"
        )


# --- Simulation of commercial flag toggle with unrelated data preservation ---


def toggle_customer_commercial_flag_with_context(
    customer: dict, new_is_commercial: bool, customer_pricing: list[dict]
) -> tuple[dict, list[dict]]:
    """
    Simulate toggling the is_commercial flag on a customer account.

    Per the specification (Requirements 5.3, 5.4):
    - The billing_email field SHALL be preserved unchanged
    - No rows in customer_pricing SHALL be inserted, updated, or deleted

    Returns the updated customer and the (unchanged) customer_pricing list.
    """
    updated_customer = {**customer, "is_commercial": new_is_commercial}
    # Safety guarantee: billing_email is independent of commercial status
    # Safety guarantee: customer_pricing is never touched by flag changes
    return updated_customer, customer_pricing


# --- Additional Strategies for Property 5 ---


_billing_email_strategy = st.one_of(
    st.none(),
    st.just(""),
    st.just("   "),
    st.emails(),
    st.text(min_size=1, max_size=50).map(lambda s: s.strip()),
)

_price_strategy = st.floats(
    min_value=0.01, max_value=9999.99, allow_nan=False, allow_infinity=False
).map(lambda x: round(x, 2))


@st.composite
def customer_pricing_rule_strategy(draw):
    """Generate a random customer_pricing rule dict."""
    return {
        "pricing_id": draw(_uuid_strategy),
        "customer_id": draw(_uuid_strategy),
        "service_id": draw(_uuid_strategy),
        "price": draw(_price_strategy),
        "is_active": draw(st.booleans()),
        "discount_percent": draw(
            st.one_of(st.none(), st.floats(min_value=0.0, max_value=100.0, allow_nan=False, allow_infinity=False))
        ),
        "notes": draw(st.one_of(st.none(), st.text(min_size=0, max_size=100))),
    }


_customer_pricing_list_strategy = st.lists(
    customer_pricing_rule_strategy(), min_size=0, max_size=15
)


@st.composite
def customer_with_billing_email_strategy(draw):
    """Generate a random customer dict with billing_email and is_commercial."""
    return {
        "customer_id": draw(_uuid_strategy),
        "email": draw(st.one_of(st.none(), st.emails())),
        "billing_email": draw(_billing_email_strategy),
        "is_commercial": draw(st.booleans()),
        "first_name": draw(st.one_of(st.none(), st.text(min_size=1, max_size=30))),
        "last_name": draw(st.one_of(st.none(), st.text(min_size=1, max_size=30))),
        "phone_number": draw(st.one_of(st.none(), st.text(min_size=5, max_size=15))),
    }


# --- Property 5 Tests ---


class TestCommercialFlagIndependenceProperty:
    """Property 5: Commercial flag independence from unrelated data.

    For any customer record, toggling is_commercial between TRUE and FALSE
    SHALL preserve the billing_email field value unchanged, and SHALL not
    insert, update, or delete any rows in shop.customer_pricing.

    **Validates: Requirements 5.3, 5.4**
    """

    @given(
        customer=customer_with_billing_email_strategy(),
        customer_pricing=_customer_pricing_list_strategy,
        new_is_commercial=st.booleans(),
    )
    @settings(max_examples=200)
    def test_billing_email_preserved_after_commercial_toggle(
        self, customer, customer_pricing, new_is_commercial
    ):
        """Toggling is_commercial preserves billing_email unchanged (Requirement 5.4).

        **Validates: Requirements 5.3, 5.4**
        """
        billing_email_before = customer.get("billing_email")

        updated_customer, _ = toggle_customer_commercial_flag_with_context(
            customer, new_is_commercial, customer_pricing
        )

        # billing_email must be unchanged regardless of the toggle
        assert updated_customer["billing_email"] == billing_email_before, (
            f"billing_email was modified after toggling is_commercial. "
            f"Before: {billing_email_before!r}, After: {updated_customer['billing_email']!r}"
        )

    @given(
        customer=customer_with_billing_email_strategy(),
        customer_pricing=_customer_pricing_list_strategy,
        new_is_commercial=st.booleans(),
    )
    @settings(max_examples=200)
    def test_customer_pricing_count_preserved_after_toggle(
        self, customer, customer_pricing, new_is_commercial
    ):
        """Toggling is_commercial does not insert or delete customer_pricing rows (Requirement 5.3).

        **Validates: Requirements 5.3, 5.4**
        """
        count_before = len(customer_pricing)
        pricing_before = copy.deepcopy(customer_pricing)

        _, pricing_after = toggle_customer_commercial_flag_with_context(
            customer, new_is_commercial, customer_pricing
        )

        # No rows inserted or deleted
        assert len(pricing_after) == count_before, (
            f"customer_pricing row count changed after toggle. "
            f"Before: {count_before}, After: {len(pricing_after)}"
        )

    @given(
        customer=customer_with_billing_email_strategy(),
        customer_pricing=_customer_pricing_list_strategy,
        new_is_commercial=st.booleans(),
    )
    @settings(max_examples=200)
    def test_customer_pricing_content_preserved_after_toggle(
        self, customer, customer_pricing, new_is_commercial
    ):
        """Toggling is_commercial does not update any customer_pricing row content (Requirement 5.3).

        **Validates: Requirements 5.3, 5.4**
        """
        pricing_before = copy.deepcopy(customer_pricing)

        _, pricing_after = toggle_customer_commercial_flag_with_context(
            customer, new_is_commercial, customer_pricing
        )

        # Every row must be identical field-by-field
        for i, (before, after) in enumerate(zip(pricing_before, pricing_after)):
            assert before == after, (
                f"customer_pricing row at index {i} was modified after toggle. "
                f"Before: {before}, After: {after}"
            )

    @given(
        customer=customer_with_billing_email_strategy(),
        customer_pricing=_customer_pricing_list_strategy,
    )
    @settings(max_examples=200)
    def test_repeated_toggles_preserve_billing_email_and_pricing(
        self, customer, customer_pricing
    ):
        """Multiple sequential toggles (True→False→True→False) preserve both
        billing_email and customer_pricing unchanged.

        **Validates: Requirements 5.3, 5.4**
        """
        billing_email_before = customer.get("billing_email")
        pricing_before = copy.deepcopy(customer_pricing)

        # Toggle: current → True
        updated_customer, pricing_step1 = toggle_customer_commercial_flag_with_context(
            customer, True, customer_pricing
        )
        # Toggle: True → False
        updated_customer, pricing_step2 = toggle_customer_commercial_flag_with_context(
            updated_customer, False, pricing_step1
        )
        # Toggle: False → True
        updated_customer, pricing_step3 = toggle_customer_commercial_flag_with_context(
            updated_customer, True, pricing_step2
        )
        # Toggle: True → False
        updated_customer, pricing_step4 = toggle_customer_commercial_flag_with_context(
            updated_customer, False, pricing_step3
        )

        # billing_email must still be the original value
        assert updated_customer["billing_email"] == billing_email_before, (
            f"billing_email changed after repeated toggles. "
            f"Before: {billing_email_before!r}, After: {updated_customer['billing_email']!r}"
        )

        # customer_pricing must be unchanged
        assert len(pricing_step4) == len(pricing_before), (
            f"customer_pricing row count changed after repeated toggles. "
            f"Before: {len(pricing_before)}, After: {len(pricing_step4)}"
        )
        for i, (before, after) in enumerate(zip(pricing_before, pricing_step4)):
            assert before == after, (
                f"customer_pricing row at index {i} was modified after repeated toggles. "
                f"Before: {before}, After: {after}"
            )

    @given(
        customer=customer_with_billing_email_strategy(),
        customer_pricing=_customer_pricing_list_strategy,
        new_is_commercial=st.booleans(),
    )
    @settings(max_examples=200)
    def test_pricing_ids_preserved_after_toggle(
        self, customer, customer_pricing, new_is_commercial
    ):
        """All pricing_id values are preserved after toggling commercial flag.
        No pricing rules are added or removed.

        **Validates: Requirements 5.3, 5.4**
        """
        ids_before = [p["pricing_id"] for p in customer_pricing]

        _, pricing_after = toggle_customer_commercial_flag_with_context(
            customer, new_is_commercial, customer_pricing
        )

        ids_after = [p["pricing_id"] for p in pricing_after]
        assert ids_before == ids_after, (
            f"Pricing IDs changed after commercial toggle. "
            f"Before: {ids_before}, After: {ids_after}"
        )
