// Shared data-model contracts for the Real-Time Garment Counter.
// These mirror the interfaces defined in the design document and are the
// single source of truth for shapes used across lib, services, store, and UI.

/** Operational counting modes; also used as the transaction `type`/`washType`. */
export type WashMode = 'Before Wash' | 'After Wash';

/**
 * Core detection event as consumed by the app. Produced by normalizing a raw
 * EC2 `/single_cloth/` response so the rest of the app is insulated from the
 * backend payload format (Requirement 2.3).
 */
export interface DetectionEvent {
  clothId: number; // Unique identifier, monotonically increasing
  clothType: string; // Category classification (e.g., "shirts", "pants")
  filePath: string; // Image path on EC2
  date: string; // ISO timestamp
  isModified: boolean; // Whether category was corrected
  washType: string; // "Before Wash" | "After Wash"
  transId: string; // Order/transaction identifier
  operatorName: string; // Employee name
  uniqId: string; // Session UUID
  status: string; // Detection status
  confidence?: number; // AI confidence 0-100 (if available)
}

/** Running per-category tally within a session. */
export interface CategoryTally {
  category: string; // e.g., "shirts"
  count: number; // Current count in this session
  items: DetectionEvent[]; // All items in this category
}

/** A bounded counting session tied to a specific order. */
export interface CountingSession {
  transId: string; // Order ID
  uniqId: string; // UUID generated by the iPad
  mode: WashMode;
  operatorName: string;
  startedAt: string; // ISO timestamp
  isActive: boolean;
  highestClothId: number; // For new-detection comparison
}

/** Before/After comparison row used for discrepancy detection. */
export interface CategoryComparison {
  category: string;
  beforeCount: number;
  afterCount: number;
  difference: number; // afterCount - beforeCount
  isResolved: boolean;
}

/** Per-server connection status shown by the two indicators. */
export interface ConnectionStatus {
  jetson: 'connected' | 'disconnected' | 'unknown';
  ec2: 'connected' | 'offline' | 'unknown';
  jetsonFailCount: number; // Consecutive failures
  ec2FailCount: number;
}

/** Settings persisted to localStorage. */
export interface AppSettings {
  jetsonUrl: string; // e.g., "http://192.168.1.100:8000"
  ec2Url: string; // e.g., "http://54.209.208.218:8000"
  audioMuted: boolean;
  knownCategories: string[]; // Persisted category list
  operatorName: string; // Last used operator name
}
